version: '3.8'
services:
  movies:
    image: swathi2706/paytm_movies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: swathi2706/paytm_train:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: swathi2706/paytm_dth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: swathi2706/paytm_recharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
