version: '3.8'
services:
  movies:
    image: swathi2706/paytm_movies1:latest
    ports:
      - "91:80"
    deploy:
      replicas: 3
  train:
    image: swathi2706/paytm_train1:latest
    ports:
      - "92:80"
    deploy:
      replicas: 3
  dth:
    image: swathi2706/paytm_dth1:latest
    ports:
      - "93:80"
    deploy:
      replicas: 3
  recharge:
    image: swathi2706/paytm_recharge1:latest
    ports:
      - "94:80"
    deploy:
      replicas: 3
