version: '3.8'
services:
  movies:
    image: swathi2706/movies1:latest
    ports:
      - "85:80"
    deploy:
      replicas: 3
  train:
    image: swathi2706/train1:latest
    ports:
      - "86:80"
    deploy:
      replicas: 3
  dth:
    image: swathi2706/dth1:latest
    ports:
      - "87:80"
    deploy:
      replicas: 3
  recharge:
    image: swathi2706/recharge1:latest
    ports:
      - "88:80"
    deploy:
      replicas: 3
